global:
  scrape_interval:     15s
  evaluation_interval: 15s
scrape_configs:
  - job_name: 'web'
    static_configs:
      - targets: ['colossus-web-svc:3000']
  - job_name: 'auth'
    static_configs:
      - targets: ['colossus-auth-svc:9092']
